spring:
  application:
    name: emailNotificationMicroservice

  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      group-id: product-created-events
      properties:
        spring:
          json:
            trusted:
              packages: "com.carlosacademic.producteventscore"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8200

