spring:
  application:
    name: emailNotificationMicroservice

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

kafka:
  bootstrap-servers: localhost:9092, localhost:9094
  group-id: product-created-events
  trusted-packages: "com.carlosacademic.producteventscore"
  consumer-isolation-level: read_committed
  auto-offset-reset: earliest

server:
  port: 8200

